Add ability to handle RNA sequence data types
qiime2/q2-types pull request #256
Opened 2021-03-24 19:16 UTC by mikerobeson

This PR adds types, formats, and transformers to handle RNA sequence data. The additions / changes are:

- Changed `DNAFASTAFormat` 
   - was updated so that it *only* accepts DNA sequences, i.e. disallows `U`
   - This was a problem as it is possible to import RNA sequence data upon import, be incorrectly called a DNA Sequence type, only to fail downstream using other QIIME 2 operations.
- Added `RNAFASTAFormat` 
   - only accepts RNA sequences disallows `T`
- Added `AlignedRNAFASTAFormat`
- Added Type `FeatureData[RNASequence]`
- Added Type `FeatureData[AlignedRNASequence]`
- Added a `NucleicAcidIterator` class to transformers. 
   - From which all other `DNA*` and `RNA*` iterators Inherit.

2021-03-29 06:51 UTC, misialq requested changes
One small thing aside, LGTM!

2021-03-29 06:51 UTC, misialq commented on q2_types/feature_data/_format.py
> +        self.alphabet = "ACGTRYKMSWBDHVN"
🙏

2021-03-29 06:51 UTC, misialq commented on q2_types/feature_data/tests/test_format.py
> +        format = DNAFASTAFormat(filepath, mode='r')
```suggestion
        format = RNAFASTAFormat(filepath, mode='r')
```

2021-03-29 16:13 UTC, mikerobeson commented on q2_types/feature_data/tests/test_format.py
> +        format = DNAFASTAFormat(filepath, mode='r')
Ohh good catch!

2021-03-30 08:21 UTC, misialq approved these changes
🚀

2021-03-30 08:23 UTC, merged