MAINT: refactor names of variables in `reference_db/tests/test_format.py`
qiime2/q2-types pull request #319
Opened 2024-04-08 14:27 UTC by Sann5

In `reference_db/tests/test_format.py` there are many variables named `dirpath`. This PR changes all of those variables to `path_to_file` which is more appropriate since they all contain paths to files and not directories.

2024-05-01 18:40 UTC, misialq requested changes
Hey @Sann5, maybe you can rather rename those to something like `filepath` or simply `fp` - no need for all this verbosity 😅

2024-05-02 12:34 UTC, Sann5 commented
> Hey @Sann5, maybe you can rather rename those to something like `filepath` or simply `fp` - no need for all this verbosity 😅

@misialq done :)

2024-05-02 13:41 UTC, misialq commented on q2_types/reference_db/tests/test_format.py
> +        fp = self.get_data_path('good_eggnog')
This is a directory.

2024-05-02 13:41 UTC, misialq commented on q2_types/reference_db/tests/test_format.py
> +        fp = self.get_data_path('single_eggnog')
Aslo a directory.

2024-05-02 13:41 UTC, misialq commented on q2_types/reference_db/tests/test_format.py
> +        fp = self.get_data_path('good_eggnog')
Same here.

2024-05-02 13:41 UTC, misialq commented on q2_types/reference_db/tests/test_format.py
> +        fp = self.get_data_path('eggnog_seq_tax')
Aaaaand here 😅

2024-05-02 14:19 UTC, Sann5 commented
@misialq shit sorry, here we go again 😅

2024-05-02 16:12 UTC, misialq approved these changes
All good, thanks! @lizgehret could you cast your eye over thins one too? Thanks! 🙏

2024-05-02 18:15 UTC, lizgehret approved these changes

2024-05-02 18:15 UTC, lizgehret commented
lgtm!

2024-05-02 18:15 UTC, merged