MAINT: adjust regex for genome data semantic types
qiime2/q2-types pull request #322
Opened 2024-04-30 12:07 UTC by Sann5

Regexes defining the file collections of semantic types `GenomeData[Loci]`, `GenomeData[Genes]`,  `GenomeData[Proteins]` had the following structure:

```python
class <name>DirectoryFormat(model.DirectoryFormat):
    <name> = model.FileCollection(r'(.*\_)?<name>[0-9]*\.<extension>$',
                                format=<format>)
```

- where `<name>` is either `loci`, `genes` or `proteins`
- `<format>` is the format of the files like FASTA of gff and `<extension>` is the associated file extension

We propose changing the regex to something like
```regex
(.*\/)?(.*)\.<extension>$
```
basically matching any random file name with an optional parent directory. The keyword `<name>` (`loci`, `genes` or `proteins`) is redundant as the specific formats are anyways linked to their respective semantic types. Ergo there is no need to indicate that in file names.

2024-05-01 18:38 UTC, misialq requested changes
Hey @Sann5,
I think you should simplify those regexes even more - there isn't really any need to have that part which recognizes slashes (since it may or may not be there, we may as well jsut get rid of it altogether). Also, you should simplify all the tests: there is no need for all those test cases with pre- and suffixes anymore - one case should be enough.

2024-05-02 13:36 UTC, Sann5 commented
@misialq done :)

2024-05-02 13:44 UTC, misialq commented on q2_types/genome_data/tests/test_format.py
>          dirpath = self.get_data_path('proteins-with-suffix')
Can you also rename al those directories to not be anymore `*-with suffix` but rather just `*` (or something along those lines)? With the updated regex we're getting rid of the whole suffix/prefix concept.

2024-05-02 14:28 UTC, Sann5 commented
@misialq I also changed some paths in the transformer tests :)

2024-05-02 16:10 UTC, misialq approved these changes
LGTM ✅ @lizgehret over to you!

2024-05-02 18:12 UTC, lizgehret commented
changes all look reasonable on my end 👍

2024-05-02 18:12 UTC, lizgehret approved these changes

2024-05-02 18:13 UTC, merged