ENH: Adds genome_dict function to `GenesDirectoryFormat` and `ProteinsDirectoryFormat`
qiime2/q2-types pull request #345
Opened 2024-10-04 16:05 UTC by VinzentRisch

closes #344

2024-10-04 16:22 UTC, VinzentRisch commented
Hi @misialq 
In sample_dict of MultiFASTADirectoryFormat you do `sample_id = d.name.rsplit('/', 1)[0]`
The  `d.name` seems to be enough why did you add the rsplit? What case does it cover? 

Also in the same action there are these checks if the files match the pathspec:
```
                if not mags_pattern.match(path.name):
                    continue
```
So it checks if the files end in fasta or fa. But isn't this redundant because in the validation of the format only files with those extensions are allowed anyway? Or am I missing something?

2024-10-07 06:57 UTC, misialq commented
Hey @VinzentRisch,

So for the `d.name` question I'm not entirely sure as, tbh, I copied this method from somewhere already 😅 When I look at it now I must agree with you: I cannot think of a use case for that split. That code looks very suggestive of the name attribute containing a full path rather than just the last piece of it, in which case we'd need to do a rsplit. If that's not the case, then I guess you can just use the name directly.

Re: matching the pathspec: that is also a good question - technically, it should not be required since, as you wrote, only those files are allowed. I guess that was more of a failsafe but you could probably skip it.

2024-10-07 07:04 UTC, misialq requested changes
Hey @VinzentRisch - so how about being a bit more generous and adding those methods to the remaining directory formats here? Loci and Genomes could also make use of those and that's what was also described in the original issue. 🙏

2024-10-07 07:04 UTC, misialq commented on q2_types/genome_data/_formats.py
> +GenesDirectoryFormat.genome_dict = genome_dict
You should not do it this way - you should rather use object inheritance. One way to do it instead would be to create a mixin which simply adds this method to each class you need it in - you can actually find an example in the MAGs directory format ;)

2024-10-07 09:05 UTC, VinzentRisch commented
Hi @misialq 
I created a new format called GenomeDataDirectoryFormat that the four dir formats can inherit from.

2024-10-08 12:22 UTC, misialq approved these changes
Hey @VinzentRisch, looks good, thanks! 🚀 

@lizgehret would you like to look this through?

2024-10-08 19:01 UTC, lizgehret approved these changes
this all looks reasonable to me, thanks @VinzentRisch!

2024-10-08 19:01 UTC, merged