ENH: collate_loci action added
qiime2/q2-types pull request #348
Opened 2024-12-11 10:52 UTC by DorielaGrabocka

PR requested by @misialq 

Adds `collate_loci` action. This action collates loci from different loci directories into a single LociDirectoryFormat and returns a GenomeData[Loci] artifact.

2024-12-13 11:28 UTC, misialq commented on q2_types/genome_data/_methods.py
> +def collate_loci(loci: LociDirectoryFormat) -> LociDirectoryFormat:
Hey @DorielaGrabocka, could you please simplify these loops to resemble the other collating actions we have in this plugin? There is one example in this file, at the bottom. Unless you had a reason to do it this way?

2025-01-09 09:17 UTC, misialq requested changes
Hey @DorielaGrabocka, could you please update the branch and resolve the conflict? Thanks! 🙏

2025-03-12 11:10 UTC, misialq approved these changes

2025-03-12 11:11 UTC, misialq commented
Hey @ebolyen and @lizgehret, this is ready for merging on my side! :)

2025-03-20 21:13 UTC, lizgehret approved these changes
lgtm!

2025-03-20 21:13 UTC, merged